### ISSUE TITLE
Publish Static Datasets

### ISSUE THREAD

**Issue by davidgasquez** [datonic/datadex#15]
We should publish datasets in multiple places

- [ ] Parquet on S3/R2
- [x] [Frictionless Packages](https://github.com/davidgasquez/datadex/issues/40)
- [ ] DuckDB file on GitHub Releases
- [x] [HuggingFace](https://github.com/davidgasquez/datadex/issues/41)
- [ ] Google Sheets?

**Comment by davidgasquez** [comment]
[Publish as parquet](https://www.robinlinacre.com/parquet_api/)!

**Comment by davidgasquez** [comment]
Also, publish via [RoAPI](https://github.com/roapi/roapi).

**Comment by davidgasquez** [comment]
Also, generate a Frictionless package (with Dagster) for the final datasets parquet files.

**Comment by davidgasquez** [comment]
Also, publish on GitHub artifacts. [Pypi does something like this](https://github.com/pypi-data/data/blob/main/.github/workflows/run.yml) for [some of their datasets](https://github.com/pypi-data/data/blob/main/links/dataset.txt)!

**Comment by fredguth** [comment]
Wow, I didn't know RoAPI, awesome!

+1 for parquet files.

**Comment by fredguth** [comment]
Maybe it is best to way to the first release version of duckdb. I head it will be soon.  Meanwhile, I would upload a parquet.

**Comment by davidgasquez** [comment]
So, datasets are being pushed to [HuggingFace](https://huggingface.co/datonic) and also exposed in the [HuggingFace API space](https://huggingface.co/spaces/datonic/API) with ROAPI!
