### ISSUE TITLE
Governance and Catalog

### ISSUE THREAD

**Issue by fredguth** [datonic/datadex#39]
I was thinking of building a "poor's man data platform" when I found datadex and it is almost everything in my wishlist.
But in a scenario where you may have many data-products, I miss a place to discover and document them. Have you considered adding a discovery and governance layer to the mix?  I am thinking about Datahub or Open-metadata. 

P.S. Not sure if this was the right way to ask. ¯\_(ツ)_/¯

**Comment by davidgasquez** [comment]
This is definitely the right way to ask! 

Glad to hear Datadex fits what you wanted to build and also, great questions.

> in a scenario where you may have many data-products, I miss a place to discover and document them

Not entirely sure what you mean by data-products there but if you're talking about models/datasets. These are some of my thoughts:

- Models can be documented both via _dbt Docs_ or by manually creating a Notebook that loops over the datasets ([example on one implementation of Datadex](https://davidgasquez.github.io/gitcoin-grants-data-portal/catalog.html)). 
- Quarto is super flexible and you can totally make a catalog or documentation with it.

These are _very_ manual approaches. To be honest is not something I've spent much time thinking about. Would love to explore it together and learn about tools or approaches that improves this process!

Will try to spend some time with Datahub or Open Metadata and report back. Also, feel free to fork the repo and try anything that might fit your needs!

**Comment by fredguth** [comment]
I will consider that... I actually like quarto very much and there is always an overhead when you add one more tool.  I have been also considering it to generate the pdf of the reports.  I recently have been using [Typst.app](https://typst.app/) (think of it like a LaTeX replacement) a lot and Quarto less and less. But I heard Quarto now can render Typst templates.

**Comment by fredguth** [comment]
Quarto and Evidence also seem to have some overlap. I am new to Evidence, but I like it is built in Svelte which I can understand better than Quarto source code.

**Comment by davidgasquez** [comment]
Nice! Been thinking about Typst recently too.

> But I heard Quarto now can render Typst templates.

Yes! It's on [their `prerelease` channel](https://quarto.org/docs/prerelease/1.4/typst.html) though.

**Comment by davidgasquez** [comment]
> Quarto and Evidence also seem to have some overlap

:100: I think Quarto is a bit more generic as it can render JS, SQL, Python, ... but Evidence looks better and has a better DX. I'm struggling between adding it or keeping it simple :see_no_evil:

**Comment by fredguth** [comment]
Typst is now part of the official release and I already created a Typst template :-)
