### ISSUE TITLE
Error creating devContainer

### ISSUE THREAD

**Issue by fredguth** [datonic/datadex#48]
Forked project and tried to open in Vscode devcontainer but there were many errors.

¡9723 ms¿ Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Users/fredguth/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/fredguth/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-d6155359-324a-473d-95ce-685f1425ff231709069914334 --workspace-folder /Users/fredguth/Code/datadex --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/fredguth/Code/datadex --id-label devcontainer.config_file=/Users/fredguth/Code/datadex/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/fredguth/Code/datadex/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root

**Comment by davidgasquez** [comment]
Closing as I think you figure it out!
