### ISSUE TITLE
[question] Best practice to start a new project with datadex

### ISSUE THREAD

**Issue by fredguth** [datonic/datadex#49]
Gitcoin, Arbitrum and Filecoin Data Portals were built with Datadex and I can see them as examples.

But I was wondering how to best translate to my use case.

I have different teams each with their domain expertise working in different data products (one team may be specialized in budgets and laws regarding municipal, state and federal level spending; other team may be specialized in costs).  They share their inexperience with git. Each team is ultimately responsible for their data products. 

In this scenario, I thought a repo per product (using a repo template) or at least per team would make more sense than one giant repo.  Building each product in a folder is enough to solve the matter of the Data Portal using quarto. But I am confused by the usage of Dagster.

I am totally new to Dagster and I saw that /datadex folder (/fdp in filecoin) has Dagster definitions, which seem to have been manually built for each project (not generated).  But eventually, I will want to deploy all my projects to the same production server where I imagine I will run one instance of Dagster, right?

**Comment by davidgasquez** [comment]
Hey! This is a very interesting question with, unfortunately, no easy answer. It all depends on things like these:

- Do you plan to reuse metrics or datasets across domains?
- Do you think the domains are clear enough for people to raise issues in the proper repository?

Without knowing many of the specifics of your use case, I'd say a great start might be having everything in the same repo and splitting later on. That way the portals evolve at the same time and there is opportunity for learning.

You can think of Dagster as the Extraction logic side. You could have 1 dagster project per data product or, have a big project covering all the data products and use dagster specific things like groups or [code locations](https://docs.dagster.io/concepts/code-locations).

**Comment by fredguth** [comment]
- There are a few dataset that are indeed used across domains
- The domains are quite different and people know which product is of which domain.

**Comment by davidgasquez** [comment]
Yes! That is what I've [been doing in the Gitcoin Data Portal](https://davidgasquez.github.io/gitcoin-grants-data-portal/catalog.html). Not the most beautiful way to do it but easy enough!
