### ISSUE TITLE
Use uv in CI

### ISSUE THREAD

**Issue by davidgasquez** [datonic/datadex#67]

**Comment by thewtex** [comment]
Worth consideration: [pixi](https://pixi.sh/latest/) = cross-platform, easy-to-write `Makefile` + `uv`

**Comment by davidgasquez** [comment]
Thanks for the rec @thewtex! Not very familiar with pixi although I've heard good things. What are the main differences with `uv` + `Makefile`?

**Comment by thewtex** [comment]
Yes, a few examples of the niceties:

- PyPI support but also `conda-forge` -> better scientific support, more reproducibility, more language support
- The *tasks* (equivalent to Makefile *targets*) are specified in a simple standard, unixy format, and they work cross-platform (including Windows)
- caching support for tasks
- oh yeah, and emoji's :sake: :space_invader: :sparkling_heart: 

[CI in action!](https://github.com/open-radiogenomics/lung-sarg/blob/ca6226b64a54c5a7fd6b9af01291f7abb0533585/.github/workflows/ci.yml#L21-L27)
[Quick datadex start!](https://github.com/open-radiogenomics/lung-sarg?tab=readme-ov-file#-pixi)

**Comment by davidgasquez** [comment]
Woah! Thanks for the details.

Caching and supporting Conda Forge sounds interesting. I think pixy does even use `uv` as their pipy dependency manager? 

The main reason I'm hessitating is that Conda is not as popular outside the "science" ecosystems and `uv` seems enough (and growing in features) for most of the usecases.

By the way, [lung-sarg](https://github.com/open-radiogenomics/lung-sarg) looks awesome! :star_struck: I see you're already even using sensors and other advanced Dagster stuff. Is it ok if I add it under the list of projects using Datadex in the README?

**Comment by thewtex** [comment]
> Caching and supporting Conda Forge sounds interesting. I think pixy does even use uv as their pipy dependency manager?

Yes, they are [working on it](https://github.com/prefix-dev/pixi/issues/1295). They plans to still keep it a single, standalone rust binary.

> The main reason I'm hessitating is that Conda is not as popular outside the "science" ecosystems and uv seems enough (and growing in features) for most of the usecases.

Ok. I get the PyPI-only and Python package-only approach. Science and reproducibility is my jam, and I have found that pixi makes sense for that use case.

> By the way, [lung-sarg](https://github.com/open-radiogenomics/lung-sarg) looks awesome! 🤩 I see you're already even using sensors and other advanced Dagster stuff. Is it ok if I add it under the list of projects using Datadex in the README?

Yes, please do!

Thank you for your work on Datadex!

**Comment by davidgasquez** [comment]
> Science and reproducibility is my jam, and I have found that pixi makes sense for that use case.

And should be everyone's jam too! :sweat_smile: I already had some issues in the past due to missmatching versions...

Seems `uv` [recently added `uv.lock` files](https://astral.sh/blog/uv-unified-python-packaging) among other things. These should be similar to `pixi.lock` and should cover the reproducibility side. 

Need to dig into that a bit more!
